// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package samplenewsapp.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import samplenewsapp.domain.NewsItemDataOnDemand;

privileged aspect NewsItemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: NewsItemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: NewsItemIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: NewsItemIntegrationTest: @Transactional;
    
    @Autowired
    private NewsItemDataOnDemand NewsItemIntegrationTest.dod;
    
    @Test
    public void NewsItemIntegrationTest.testCountNewsItems() {
        org.junit.Assert.assertNotNull("Data on demand for 'NewsItem' failed to initialize correctly", dod.getRandomNewsItem());
        long count = samplenewsapp.domain.NewsItem.countNewsItems();
        org.junit.Assert.assertTrue("Counter for 'NewsItem' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void NewsItemIntegrationTest.testFindNewsItem() {
        samplenewsapp.domain.NewsItem obj = dod.getRandomNewsItem();
        org.junit.Assert.assertNotNull("Data on demand for 'NewsItem' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'NewsItem' failed to provide an identifier", id);
        obj = samplenewsapp.domain.NewsItem.findNewsItem(id);
        org.junit.Assert.assertNotNull("Find method for 'NewsItem' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'NewsItem' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void NewsItemIntegrationTest.testFindAllNewsItems() {
        org.junit.Assert.assertNotNull("Data on demand for 'NewsItem' failed to initialize correctly", dod.getRandomNewsItem());
        long count = samplenewsapp.domain.NewsItem.countNewsItems();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'NewsItem', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<samplenewsapp.domain.NewsItem> result = samplenewsapp.domain.NewsItem.findAllNewsItems();
        org.junit.Assert.assertNotNull("Find all method for 'NewsItem' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'NewsItem' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void NewsItemIntegrationTest.testFindNewsItemEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'NewsItem' failed to initialize correctly", dod.getRandomNewsItem());
        long count = samplenewsapp.domain.NewsItem.countNewsItems();
        if (count > 20) count = 20;
        java.util.List<samplenewsapp.domain.NewsItem> result = samplenewsapp.domain.NewsItem.findNewsItemEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'NewsItem' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'NewsItem' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void NewsItemIntegrationTest.testFlush() {
        samplenewsapp.domain.NewsItem obj = dod.getRandomNewsItem();
        org.junit.Assert.assertNotNull("Data on demand for 'NewsItem' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'NewsItem' failed to provide an identifier", id);
        obj = samplenewsapp.domain.NewsItem.findNewsItem(id);
        org.junit.Assert.assertNotNull("Find method for 'NewsItem' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyNewsItem(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'NewsItem' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NewsItemIntegrationTest.testMerge() {
        samplenewsapp.domain.NewsItem obj = dod.getRandomNewsItem();
        org.junit.Assert.assertNotNull("Data on demand for 'NewsItem' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'NewsItem' failed to provide an identifier", id);
        obj = samplenewsapp.domain.NewsItem.findNewsItem(id);
        boolean modified =  dod.modifyNewsItem(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        samplenewsapp.domain.NewsItem merged = (samplenewsapp.domain.NewsItem) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'NewsItem' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NewsItemIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'NewsItem' failed to initialize correctly", dod.getRandomNewsItem());
        samplenewsapp.domain.NewsItem obj = dod.getNewTransientNewsItem(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'NewsItem' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'NewsItem' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'NewsItem' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void NewsItemIntegrationTest.testRemove() {
        samplenewsapp.domain.NewsItem obj = dod.getRandomNewsItem();
        org.junit.Assert.assertNotNull("Data on demand for 'NewsItem' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'NewsItem' failed to provide an identifier", id);
        obj = samplenewsapp.domain.NewsItem.findNewsItem(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'NewsItem' with identifier '" + id + "'", samplenewsapp.domain.NewsItem.findNewsItem(id));
    }
    
}
